	class SFPD_RHS_SAV_WOODLAND_M1151A1: rhssaf_m1151_olive {
		SFPD_VEHICLES_CFG(SFPD_RHS_SAV_WOODLAND_Faction,SFPD_RHS_SAV_WOODLAND_Rifleman)
		SFPD_RHS_SAV_Transport
	};
	
	class SFPD_RHS_SAV_WOODLAND_M1151A1_GPK_PKM: rhssaf_m1151_olive_pkm {
		SFPD_VEHICLES_CFG(SFPD_RHS_SAV_WOODLAND_Faction,SFPD_RHS_SAV_WOODLAND_Rifleman)
		SFPD_RHS_SAV_Transport
	};
	
	class SFPD_RHS_SAV_WOODLAND_ural: rhssaf_army_ural_open {
		SFPD_VEHICLES_CFG(SFPD_RHS_SAV_WOODLAND_Faction,SFPD_RHS_SAV_WOODLAND_Rifleman)
		SFPD_RHS_SAV_Transport
	};