
	class SFPD_RHS_FR_WOODLAND_OFrP_P4_FR_CE: OFrP_P4_FR_CE {
		SFPD_VEHICLES_CFG(SFPD_RHS_FR_WOODLAND_Faction,SFPD_RHS_FR_WOODLAND_Rifleman)
		SFPD_RHS_FR_Transport
	};
	
	class SFPD_RHS_FR_WOODLAND_OFrP_P4_AANF1_FR_CE: OFrP_P4_AANF1_FR_CE {
		SFPD_VEHICLES_CFG(SFPD_RHS_FR_WOODLAND_Faction,SFPD_RHS_FR_WOODLAND_Rifleman)
		SFPD_RHS_FR_Transport
	};
	
	class SFPD_RHS_FR_WOODLAND_OFrP_P4_PATSAS_M2_AANF1_1_FR_CE: OFrP_P4_PATSAS_M2_AANF1_1_FR_CE {
		SFPD_VEHICLES_CFG(SFPD_RHS_FR_WOODLAND_Faction,SFPD_RHS_FR_WOODLAND_Rifleman)
		SFPD_RHS_FR_Transport
	};