		class SFPD_BLUFOR_DESERT_Faction {
			name = "[SFPD] NATO (Desert)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_DESERT_Leader,SFPD_BLUFOR_DESERT_Rifleman,SFPD_BLUFOR_DESERT_AT,SFPD_BLUFOR_DESERT_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_DESERT_Leader,SFPD_BLUFOR_DESERT_Medic,SFPD_BLUFOR_DESERT_Rifleman,SFPD_BLUFOR_DESERT_LMG,SFPD_BLUFOR_DESERT_Rifleman,SFPD_BLUFOR_DESERT_Medic,SFPD_BLUFOR_DESERT_AT,SFPD_BLUFOR_DESERT_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_DESERT_Rifleman_light,SFPD_BLUFOR_DESERT_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_BLUFOR_DESERT_SF_Leader,SFPD_BLUFOR_DESERT_SF_Grenadier,SFPD_BLUFOR_DESERT_SF_AT,SFPD_BLUFOR_DESERT_SF_LMG)
			};
		};
		
		class SFPD_BLUFOR_WOODLAND_Faction {
			name = "[SFPD] NATO (Woodland)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_WOODLAND_Leader,SFPD_BLUFOR_WOODLAND_Rifleman,SFPD_BLUFOR_WOODLAND_AT,SFPD_BLUFOR_WOODLAND_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_WOODLAND_Leader,SFPD_BLUFOR_WOODLAND_Medic,SFPD_BLUFOR_WOODLAND_Rifleman,SFPD_BLUFOR_WOODLAND_LMG,SFPD_BLUFOR_WOODLAND_Rifleman,SFPD_BLUFOR_WOODLAND_Medic,SFPD_BLUFOR_WOODLAND_AT,SFPD_BLUFOR_WOODLAND_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_WOODLAND_Rifleman_light,SFPD_BLUFOR_WOODLAND_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_BLUFOR_WOODLAND_SF_Leader,SFPD_BLUFOR_WOODLAND_SF_Grenadier,SFPD_BLUFOR_WOODLAND_SF_AT,SFPD_BLUFOR_WOODLAND_SF_LMG)
			};
		};
		
		class SFPD_BLUFOR_JUNGLE_Faction {
			name = "[SFPD] NATO (Jungle)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_BLUFOR_JUNGLE_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_JUNGLE_Leader,SFPD_BLUFOR_JUNGLE_Rifleman,SFPD_BLUFOR_JUNGLE_AT,SFPD_BLUFOR_JUNGLE_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_BLUFOR_JUNGLE_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_JUNGLE_Leader,SFPD_BLUFOR_JUNGLE_Medic,SFPD_BLUFOR_JUNGLE_Rifleman,SFPD_BLUFOR_JUNGLE_LMG,SFPD_BLUFOR_JUNGLE_Rifleman,SFPD_BLUFOR_JUNGLE_Medic,SFPD_BLUFOR_JUNGLE_AT,SFPD_BLUFOR_JUNGLE_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_BLUFOR_JUNGLE_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_BLUFOR_JUNGLE_Rifleman_light,SFPD_BLUFOR_JUNGLE_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_BLUFOR_JUNGLE_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_BLUFOR_JUNGLE_SF_Leader,SFPD_BLUFOR_JUNGLE_SF_Grenadier,SFPD_BLUFOR_JUNGLE_SF_AT,SFPD_BLUFOR_JUNGLE_SF_LMG)
			};
		};