		class SFPD_RHS_BLUFOR_DESERT_Faction {
			name = "[SFPD RHS] US (Desert)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_RHS_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_DESERT_Leader,SFPD_RHS_BLUFOR_DESERT_Rifleman,SFPD_RHS_BLUFOR_DESERT_AT_M136,SFPD_RHS_BLUFOR_DESERT_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_RHS_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_DESERT_Leader,SFPD_RHS_BLUFOR_DESERT_Medic,SFPD_RHS_BLUFOR_DESERT_Rifleman,SFPD_RHS_BLUFOR_DESERT_LMG,SFPD_RHS_BLUFOR_DESERT_Rifleman,SFPD_RHS_BLUFOR_DESERT_Medic,SFPD_RHS_BLUFOR_DESERT_AT,SFPD_RHS_BLUFOR_DESERT_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_RHS_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_DESERT_Rifleman_light,SFPD_RHS_BLUFOR_DESERT_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_RHS_BLUFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_RHS_BLUFOR_DESERT_SF_Leader,SFPD_RHS_BLUFOR_DESERT_SF_Grenadier,SFPD_RHS_BLUFOR_DESERT_SF_AT,SFPD_RHS_BLUFOR_DESERT_SF_LMG)
			};
		};
		
		class SFPD_RHS_BLUFOR_WOODLAND_Faction {
			name = "[SFPD RHS] US (Woodland)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_RHS_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WOODLAND_Leader,SFPD_RHS_BLUFOR_WOODLAND_Rifleman,SFPD_RHS_BLUFOR_WOODLAND_AT_M136,SFPD_RHS_BLUFOR_WOODLAND_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_RHS_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WOODLAND_Leader,SFPD_RHS_BLUFOR_WOODLAND_Medic,SFPD_RHS_BLUFOR_WOODLAND_Rifleman,SFPD_RHS_BLUFOR_WOODLAND_LMG,SFPD_RHS_BLUFOR_WOODLAND_Rifleman,SFPD_RHS_BLUFOR_WOODLAND_Medic,SFPD_RHS_BLUFOR_WOODLAND_AT,SFPD_RHS_BLUFOR_WOODLAND_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_RHS_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WOODLAND_Rifleman_light,SFPD_RHS_BLUFOR_WOODLAND_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_RHS_BLUFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_RHS_BLUFOR_WOODLAND_SF_Leader,SFPD_RHS_BLUFOR_WOODLAND_SF_Grenadier,SFPD_RHS_BLUFOR_WOODLAND_SF_AT,SFPD_RHS_BLUFOR_WOODLAND_SF_LMG)
			};
		};
		
		class SFPD_RHS_BLUFOR_WINTER_Faction {
			name = "[SFPD RHS] US (Winter)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(1,SFPD_RHS_BLUFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WINTER_Leader,SFPD_RHS_BLUFOR_WINTER_Rifleman,SFPD_RHS_BLUFOR_WINTER_AT_M136,SFPD_RHS_BLUFOR_WINTER_LMG)
				SFPD_GROUP_SQUAD_CFG(1,SFPD_RHS_BLUFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WINTER_Leader,SFPD_RHS_BLUFOR_WINTER_Medic,SFPD_RHS_BLUFOR_WINTER_Rifleman,SFPD_RHS_BLUFOR_WINTER_LMG,SFPD_RHS_BLUFOR_WINTER_Rifleman,SFPD_RHS_BLUFOR_WINTER_Medic,SFPD_RHS_BLUFOR_WINTER_AT,SFPD_RHS_BLUFOR_WINTER_Marksman)
				SFPD_GROUP_PATROL_CFG(1,SFPD_RHS_BLUFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\b_inf.paa,SFPD_RHS_BLUFOR_WINTER_Rifleman_light,SFPD_RHS_BLUFOR_WINTER_Rifleman_light)
				SFPD_GROUP_SFT_CFG(1,SFPD_RHS_BLUFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\b_recon.paa,SFPD_RHS_BLUFOR_WINTER_SF_Leader,SFPD_RHS_BLUFOR_WINTER_SF_Grenadier,SFPD_RHS_BLUFOR_WINTER_SF_AT,SFPD_RHS_BLUFOR_WINTER_SF_LMG)
			};
		};