		class SFPD_RHS_OPFOR_DESERT_Faction {
			name = "[SFPD RHS] RU (Desert)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(0,SFPD_RHS_OPFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_DESERT_Leader,SFPD_RHS_OPFOR_DESERT_Rifleman,SFPD_RHS_OPFOR_DESERT_AT,SFPD_RHS_OPFOR_DESERT_LMG)
				SFPD_GROUP_SQUAD_CFG(0,SFPD_RHS_OPFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_DESERT_Leader,SFPD_RHS_OPFOR_DESERT_Medic,SFPD_RHS_OPFOR_DESERT_Rifleman,SFPD_RHS_OPFOR_DESERT_LMG,SFPD_RHS_OPFOR_DESERT_Rifleman,SFPD_RHS_OPFOR_DESERT_Medic,SFPD_RHS_OPFOR_DESERT_AT,SFPD_RHS_OPFOR_DESERT_Marksman)
				SFPD_GROUP_PATROL_CFG(0,SFPD_RHS_OPFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_DESERT_Rifleman_light,SFPD_RHS_OPFOR_DESERT_Rifleman_light)
				SFPD_GROUP_SFT_CFG(0,SFPD_RHS_OPFOR_DESERT_Faction,\A3\ui_f\data\map\markers\nato\o_recon.paa,SFPD_RHS_OPFOR_DESERT_SF_Leader,SFPD_RHS_OPFOR_DESERT_SF_Grenadier,SFPD_RHS_OPFOR_DESERT_SF_AT,SFPD_RHS_OPFOR_DESERT_SF_LMG)
			};
		};
		
		class SFPD_RHS_OPFOR_WOODLAND_Faction {
			name = "[SFPD RHS] RU (Woodland)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(0,SFPD_RHS_OPFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WOODLAND_Leader,SFPD_RHS_OPFOR_WOODLAND_Rifleman,SFPD_RHS_OPFOR_WOODLAND_AT,SFPD_RHS_OPFOR_WOODLAND_LMG)
				SFPD_GROUP_SQUAD_CFG(0,SFPD_RHS_OPFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WOODLAND_Leader,SFPD_RHS_OPFOR_WOODLAND_Medic,SFPD_RHS_OPFOR_WOODLAND_Rifleman,SFPD_RHS_OPFOR_WOODLAND_LMG,SFPD_RHS_OPFOR_WOODLAND_Rifleman,SFPD_RHS_OPFOR_WOODLAND_Medic,SFPD_RHS_OPFOR_WOODLAND_AT,SFPD_RHS_OPFOR_WOODLAND_Marksman)
				SFPD_GROUP_PATROL_CFG(0,SFPD_RHS_OPFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WOODLAND_Rifleman_light,SFPD_RHS_OPFOR_WOODLAND_Rifleman_light)
				SFPD_GROUP_SFT_CFG(0,SFPD_RHS_OPFOR_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\o_recon.paa,SFPD_RHS_OPFOR_WOODLAND_SF_Leader,SFPD_RHS_OPFOR_WOODLAND_SF_Grenadier,SFPD_RHS_OPFOR_WOODLAND_SF_AT,SFPD_RHS_OPFOR_WOODLAND_SF_LMG)
			};
		};
		
		class SFPD_RHS_OPFOR_WINTER_Faction {
			name = "[SFPD RHS] RU (Winter)";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(0,SFPD_RHS_OPFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WINTER_Leader,SFPD_RHS_OPFOR_WINTER_Rifleman,SFPD_RHS_OPFOR_WINTER_AT,SFPD_RHS_OPFOR_WINTER_LMG)
				SFPD_GROUP_SQUAD_CFG(0,SFPD_RHS_OPFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WINTER_Leader,SFPD_RHS_OPFOR_WINTER_Medic,SFPD_RHS_OPFOR_WINTER_Rifleman,SFPD_RHS_OPFOR_WINTER_LMG,SFPD_RHS_OPFOR_WINTER_Rifleman,SFPD_RHS_OPFOR_WINTER_Medic,SFPD_RHS_OPFOR_WINTER_AT,SFPD_RHS_OPFOR_WINTER_Marksman)
				SFPD_GROUP_PATROL_CFG(0,SFPD_RHS_OPFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\o_inf.paa,SFPD_RHS_OPFOR_WINTER_Rifleman_light,SFPD_RHS_OPFOR_WINTER_Rifleman_light)
				SFPD_GROUP_SFT_CFG(0,SFPD_RHS_OPFOR_WINTER_Faction,\A3\ui_f\data\map\markers\nato\o_recon.paa,SFPD_RHS_OPFOR_WINTER_SF_Leader,SFPD_RHS_OPFOR_WINTER_SF_Grenadier,SFPD_RHS_OPFOR_WINTER_SF_AT,SFPD_RHS_OPFOR_WINTER_SF_LMG)
			};
		};