		class SFPD_RHS_IRAQ_WOODLAND_Faction {
			name = "[SFPD RHS] IRAQ";
			class Infantry {
				name = "Infantry";
				SFPD_GROUP_FT_CFG(2,SFPD_RHS_IRAQ_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\n_inf.paa,SFPD_RHS_IRAQ_WOODLAND_Leader,SFPD_RHS_IRAQ_WOODLAND_Rifleman,SFPD_RHS_IRAQ_WOODLAND_AT,SFPD_RHS_IRAQ_WOODLAND_LMG)
				SFPD_GROUP_SQUAD_CFG(2,SFPD_RHS_IRAQ_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\n_inf.paa,SFPD_RHS_IRAQ_WOODLAND_Leader,SFPD_RHS_IRAQ_WOODLAND_Medic,SFPD_RHS_IRAQ_WOODLAND_Rifleman,SFPD_RHS_IRAQ_WOODLAND_LMG,SFPD_RHS_IRAQ_WOODLAND_Rifleman,SFPD_RHS_IRAQ_WOODLAND_Medic,SFPD_RHS_IRAQ_WOODLAND_AT,SFPD_RHS_IRAQ_WOODLAND_Marksman)
				SFPD_GROUP_PATROL_CFG(2,SFPD_RHS_IRAQ_WOODLAND_Faction,\A3\ui_f\data\map\markers\nato\n_inf.paa,SFPD_RHS_IRAQ_WOODLAND_Rifleman_light,SFPD_RHS_IRAQ_WOODLAND_Rifleman_light)
			};
		};