	//Desert
	class SFPD_BLUFOR_DESERT_Prowler_U: B_LSV_01_unarmed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Prowler_A: B_LSV_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Prowler_AT: B_LSV_01_AT_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Hunter: B_MRAP_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Pickup_aa: B_Pickup_aat_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Pickup: B_Pickup_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Pickup_Comms: B_Pickup_Comms_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Pickup_mmg: B_Pickup_mmg_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT: B_Truck_01_transport_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_cargo: B_Truck_01_cargo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Badger: B_APC_Wheeled_01_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Badger_ATGM: APC_Wheeled_01_atgm_base_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Badger_GMG: APC_Wheeled_01_command_base_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Badger_mortar: APC_Wheeled_01_mortar_base_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Namer: B_APC_Tracked_01_rcws_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Nemmera: B_APC_Tracked_01_CRV_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Merkava: B_MBT_01_TUSK_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Rhino: B_AFV_Wheeled_01_up_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_A: B_Truck_01_ammo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_F: B_Truck_01_fuel_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_M: B_Truck_01_medical_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_FB: B_Truck_01_flatbed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_AA: B_APC_Tracked_01_AA_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_MLRS: B_MBT_01_mlrs_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Howitzer: B_MBT_01_arty_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_TankCrew)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Boat: B_Boat_Transport_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_RHIB: I_C_Boat_Transport_02_F {
		side = 1;
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_Speedboat: B_Boat_Armed_01_minigun_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_Empty: B_Truck_01_mover_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_HEMTT_C: B_Truck_01_box_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Hunter_HMG: B_MRAP_01_hmg_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_Quad: B_Quadbike_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_MH6: B_Heli_Light_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_GhostHawk: B_CTRG_Heli_Transport_01_sand_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_Huron: B_Heli_Transport_03_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_AH6: B_Heli_Light_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_Comanche: B_Heli_Attack_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_ah11f: B_Heli_light_03_dynamicLoadout_RF {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_ah11f_unarmed: B_Heli_light_03_unarmed_RF {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_mh_245: B_Heli_EC_03_RF {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_mh_245_unarmed: B_Heli_EC_04_military_RF {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_BlackFish_I: B_T_VTOL_01_infantry_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_BlackFish_V: B_T_VTOL_01_vehicle_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_BlackFish_A: B_T_VTOL_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_A10: B_Plane_CAS_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_A10_Cluster: B_Plane_CAS_01_Cluster_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_BlackWasp: B_Plane_Fighter_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_MRAP_01_FSV_NATO: EF_B_MRAP_01_FSV_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_MRAP_01_AT_NATO: EF_B_MRAP_01_AT_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_MRAP_01_LAAD_NATO: EF_B_MRAP_01_LAAD_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_B_Truck_01_FFT_rf: B_Truck_01_FFT_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_CombatBoat_Unarmed_NATO: EF_B_CombatBoat_Unarmed_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_CombatBoat_HMG_NATO: EF_B_CombatBoat_HMG_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_CombatBoat_AT_NATO: EF_B_CombatBoat_AT_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_B_Heli_Transport_01_pylons_F: B_Heli_Transport_01_pylons_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_AH99J_NATO: EF_B_AH99J_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_B_Heli_Attack_01_pylons_dynamicLoadout_F: B_Heli_Attack_01_pylons_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_AAV9_MJTF_Des: EF_B_AAV9_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_AAV9_50mm_MJTF_Des: EF_B_AAV9_50mm_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_LCC_MJTF_Des: EF_B_LCC_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	class SFPD_BLUFOR_DESERT_EF_B_LCC_SideLoad_MJTF_Des: EF_B_LCC_SideLoad_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_DESERT_Faction,SFPD_BLUFOR_DESERT_Rifleman)
		SFPD_BLUFOR_DESERT_Transport
	};
	
	//Woodland
	class SFPD_BLUFOR_WOODLAND_Prowler_U: B_T_LSV_01_unarmed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Prowler_A: B_T_LSV_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Prowler_AT: B_T_LSV_01_AT_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Hunter: B_T_MRAP_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Pickup_aa: B_T_Pickup_aat_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Pickup: B_T_Pickup_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Pickup_Comms: B_T_Pickup_Comms_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Pickup_mmg: B_T_Pickup_mmg_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT: B_T_Truck_01_transport_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_cargo: B_T_Truck_01_cargo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Badger: B_T_APC_Wheeled_01_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Badger_ATGM: B_T_APC_Wheeled_01_atgm_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Badger_GMG: B_T_APC_Wheeled_01_command_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Badger_mortar: B_T_APC_Wheeled_01_mortar_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Namer: B_T_APC_Tracked_01_rcws_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Nemmera: B_T_APC_Tracked_01_CRV_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Merkava: B_T_MBT_01_TUSK_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Rhino: B_T_AFV_Wheeled_01_up_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_A: B_T_Truck_01_ammo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_F: B_T_Truck_01_fuel_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_M: B_T_Truck_01_medical_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_FB: B_T_Truck_01_flatbed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_AA: B_T_APC_Tracked_01_AA_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_MLRS: B_T_MBT_01_mlrs_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Howitzer: B_T_MBT_01_arty_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_TankCrew)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Boat: B_Boat_Transport_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_RHIB: I_C_Boat_Transport_02_F {
		side = 1;
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_Speedboat: B_Boat_Armed_01_minigun_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_Empty: B_T_Truck_01_mover_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_HEMTT_C: B_T_Truck_01_box_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Hunter_HMG: B_T_MRAP_01_hmg_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_Quad: B_T_Quadbike_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_MH6: B_Heli_Light_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_GhostHawk: B_CTRG_Heli_Transport_01_tropic_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_Huron: B_Heli_Transport_03_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_AH6: B_Heli_Light_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_Comanche: B_Heli_Attack_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_BlackFish_I: B_T_VTOL_01_infantry_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_BlackFish_V: B_T_VTOL_01_vehicle_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_BlackFish_A: B_T_VTOL_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_A10: B_Plane_CAS_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_A10_Cluster: B_Plane_CAS_01_Cluster_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_BlackWasp: B_Plane_Fighter_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_MRAP_01_FSV_NATO_T: EF_B_MRAP_01_FSV_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_MRAP_01_AT_NATO_T: EF_B_MRAP_01_AT_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_MRAP_01_LAAD_NATO_T: EF_B_MRAP_01_LAAD_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_B_T_Truck_01_FFT_rf: B_T_Truck_01_FFT_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_CombatBoat_Unarmed_NATO: EF_B_CombatBoat_Unarmed_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_CombatBoat_HMG_NATO: EF_B_CombatBoat_HMG_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_CombatBoat_AT_NATO: EF_B_CombatBoat_AT_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_B_Heli_Transport_01_pylons_F: B_Heli_Transport_01_pylons_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_AH99J_NATO: EF_B_AH99J_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_B_Heli_Attack_01_pylons_dynamicLoadout_F: B_Heli_Attack_01_pylons_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_AAV9_MJTF_Wdl: EF_B_AAV9_MJTF_Wdl {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_AAV9_50mm_MJTF_Wdl: EF_B_AAV9_50mm_MJTF_Wdl {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_LCC_MJTF_Des: EF_B_LCC_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	class SFPD_BLUFOR_WOODLAND_EF_B_LCC_SideLoad_MJTF_Des: EF_B_LCC_SideLoad_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_WOODLAND_Faction,SFPD_BLUFOR_WOODLAND_Rifleman)
		SFPD_BLUFOR_WOODLAND_Transport
	};
	
	//Jungle
	class SFPD_BLUFOR_JUNGLE_Prowler_U: B_T_LSV_01_unarmed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Prowler_A: B_T_LSV_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Prowler_AT: B_T_LSV_01_AT_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Hunter: B_T_MRAP_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Pickup_aa: B_T_Pickup_aat_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Pickup: B_T_Pickup_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Pickup_Comms: B_T_Pickup_Comms_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Pickup_mmg: B_T_Pickup_mmg_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT: B_T_Truck_01_transport_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_cargo: B_T_Truck_01_cargo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Badger: B_T_APC_Wheeled_01_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Badger_ATGM: B_T_APC_Wheeled_01_atgm_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Badger_GMG: B_T_APC_Wheeled_01_command_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Badger_mortar: B_T_APC_Wheeled_01_mortar_lxWS {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Namer: B_T_APC_Tracked_01_rcws_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Nemmera: B_T_APC_Tracked_01_CRV_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Merkava: B_T_MBT_01_TUSK_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Rhino: B_T_AFV_Wheeled_01_up_cannon_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_A: B_T_Truck_01_ammo_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_F: B_T_Truck_01_fuel_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_M: B_T_Truck_01_medical_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_FB: B_T_Truck_01_flatbed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_AA: B_T_APC_Tracked_01_AA_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_MLRS: B_T_MBT_01_mlrs_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Howitzer: B_T_MBT_01_arty_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_TankCrew)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Boat: B_Boat_Transport_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_RHIB: I_C_Boat_Transport_02_F {
		side = 1;
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_Speedboat: B_Boat_Armed_01_minigun_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_Empty: B_T_Truck_01_mover_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_HEMTT_C: B_T_Truck_01_box_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Hunter_HMG: B_T_MRAP_01_hmg_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_Quad: B_T_Quadbike_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_MH6: B_Heli_Light_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_GhostHawk: B_CTRG_Heli_Transport_01_tropic_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_Huron: B_Heli_Transport_03_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_AH6: B_Heli_Light_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_Comanche: B_Heli_Attack_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_BlackFish_I: B_T_VTOL_01_infantry_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_BlackFish_V: B_T_VTOL_01_vehicle_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_BlackFish_A: B_T_VTOL_01_armed_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_A10: B_Plane_CAS_01_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_A10_Cluster: B_Plane_CAS_01_Cluster_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_BlackWasp: B_Plane_Fighter_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_PlanePilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_MRAP_01_FSV_NATO_T: EF_B_MRAP_01_FSV_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_MRAP_01_AT_NATO_T: EF_B_MRAP_01_AT_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_MRAP_01_LAAD_NATO_T: EF_B_MRAP_01_LAAD_NATO_T {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_B_T_Truck_01_FFT_rf: B_T_Truck_01_FFT_rf {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_CombatBoat_Unarmed_NATO: EF_B_CombatBoat_Unarmed_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_CombatBoat_HMG_NATO: EF_B_CombatBoat_HMG_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_CombatBoat_AT_NATO: EF_B_CombatBoat_AT_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_B_Heli_Transport_01_pylons_F: B_Heli_Transport_01_pylons_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_AH99J_NATO: EF_B_AH99J_NATO {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_B_Heli_Attack_01_pylons_dynamicLoadout_F: B_Heli_Attack_01_pylons_dynamicLoadout_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_HelicopterPilot)
		SFPD_VEHICLES_EMPTY_CARGO
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_AAV9_MJTF_Wdl: EF_B_AAV9_MJTF_Wdl {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_AAV9_50mm_MJTF_Wdl: EF_B_AAV9_50mm_MJTF_Wdl {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_LCC_MJTF_Des: EF_B_LCC_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	class SFPD_BLUFOR_JUNGLE_EF_B_LCC_SideLoad_MJTF_Des: EF_B_LCC_SideLoad_MJTF_Des {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_JUNGLE_Faction,SFPD_BLUFOR_JUNGLE_Rifleman)
		SFPD_BLUFOR_JUNGLE_Transport
	};
	
	//Universal
	class SFPD_BLUFOR_SDV: B_SDV_01_F {
		SFPD_VEHICLES_CFG(SFPD_BLUFOR_Faction,SFPD_BLUFOR_Diver)
		SFPD_VEHICLES_EMPTY_CARGO
	};